// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8GcNX7mfO36nBXYy2cRREHteKwBbw1tI',
    appId: '1:373747646954:web:26519367c6a40a5d10b293',
    messagingSenderId: '373747646954',
    projectId: 'neighborly-3cb66',
    authDomain: 'neighborly-3cb66.firebaseapp.com',
    storageBucket: 'neighborly-3cb66.firebasestorage.app',
    measurementId: 'G-JTMFCX47T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdh5Av2TXNQ-u_YrckY709BmRWFCNWdc',
    appId: '1:373747646954:android:af556f9e011e0ffb10b293',
    messagingSenderId: '373747646954',
    projectId: 'neighborly-3cb66',
    storageBucket: 'neighborly-3cb66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4FiWgftm8tHSxczbQANHodVse6G1j7Jk',
    appId: '1:373747646954:ios:7620656f0ecfcce810b293',
    messagingSenderId: '373747646954',
    projectId: 'neighborly-3cb66',
    storageBucket: 'neighborly-3cb66.firebasestorage.app',
    iosBundleId: 'com.example.neighborly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4FiWgftm8tHSxczbQANHodVse6G1j7Jk',
    appId: '1:373747646954:ios:7620656f0ecfcce810b293',
    messagingSenderId: '373747646954',
    projectId: 'neighborly-3cb66',
    storageBucket: 'neighborly-3cb66.firebasestorage.app',
    iosBundleId: 'com.example.neighborly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8GcNX7mfO36nBXYy2cRREHteKwBbw1tI',
    appId: '1:373747646954:web:26519367c6a40a5d10b293',
    messagingSenderId: '373747646954',
    projectId: 'neighborly-3cb66',
    authDomain: 'neighborly-3cb66.firebaseapp.com',
    storageBucket: 'neighborly-3cb66.firebasestorage.app',
    measurementId: 'G-JTMFCX47T4',
  );
}
